### PR TITLE
CC-15732: Add support for range property with logical decimal types (bytes only)

### PR DESCRIPTION
**Pull request by C0urante**
[Jira](https://confluentinc.atlassian.net/browse/CC-15732)

Adds support for the `range` attribute (containing `min` and/or `max` elements) to the logical decimal type.

Only decimals using the backing `bytes` type are supported; the `fixed` type is left unsupported.

The version is bumped to `0.4.0-SNAPSHOT` as this is a new feature and not a bug fix.

Implemented in response to a use case identified with https://github.com/confluentinc/kafka-connect-datagen/pull/89#discussion_r708510102.

### CODE REVIEW

**Comment by C0urante** [comment]
cc @ybyzek Hope this was quick enough :)

**Review by ybyzek — APPROVED** [review]
@C0urante ⚡ fast PR!  I'm not familiar enough to do a code review but otherwise LGTM in terms of adding support for decimals and ranges, thank you! 

Note: I tried to test this locally but I am running Gradle 7.0 in my environment and thus the project wouldn't build due to 

```
Could not compile build file '/Users/yeva/git/avro-random-generator/build.gradle'.
> startup failed:
  build file '/Users/yeva/git/avro-random-generator/build.gradle': 82: unable to resolve class MavenDeployment 
   @ line 82, column 30.
                 beforeDeployment {
```

See https://discuss.gradle.org/t/mavendeployment-deprecated-with-gradle-6-3/36096 , this was deprecated in 6.3 and removed in 7.0: https://github.com/lottie-react-native/lottie-react-native/issues/794 .  

IIUC many folks are now running 7.0 (e.g. I had to upgrade to 7.0 for another project) so it would be good to address this, upgrading `MavenDeployment` to `Maven Publish`.  I don't have repo permissions to file an issue here.

**Comment by C0urante** [comment]
Thanks Yeva!

We verified offline with a snapshot build of the Datagen connector that this feature works as expected; will merge and put out a new 0.4.0 release.

**Comment by ybyzek** [comment]
🥳 @C0urante

**Pull request merged**
