### PR TITLE
Removed the dependency on findbugs because it is LGPL and that can ca…

### PR DESCRIPTION
**Pull request by MikeThomsen**
…use problems for commercial organizations and ASF projects.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
@big-andy-coates @C0urante I'd like to use this to build a data generator for Apache NiFi, but we cannot bundle LGPL transitive dependencies.

**Comment by MikeThomsen** [comment]
Thanks!

**Comment by C0urante** [comment]
Hi @MikeThomsen,

1. I'll go ahead and cut an `0.2.1` release Monday (tomorrow). Until then, the [most recent release](https://search.maven.org/#artifactdetails%7Cio.confluent.avro%7Cavro-random-generator%7C0.2.0%7Cjar) on Maven Central is functionally identical to the current master branch, but with the Findbugs dependency you noted. Feel free to just bundle `Generator.java` if you'd like, though.
2. The attribution should be directed at Confluent.

**Comment by C0urante** [comment]
@MikeThomsen The `0.2.1` release is now available in Maven Central: https://repo1.maven.org/maven2/io/confluent/avro/avro-random-generator/0.2.1/
Sorry for the delay, I performed the upload yesterday but there seemed to be some issues with Maven and it wasn't visible in the central repository until I checked again this morning.

**Pull request merged**
